name: Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci

      - run: npm run compile

      - run: ./publish.sh
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.PAT_MARKETPLACE }}
          DEPLOY: production

      - uses: actions/upload-artifact@v2
        with:
          name: VSIX
          path: out/*.vsix
